# Generated by roxytest: Do not edit by hand!

context("File R/show_seq_logo.R: @testexamples")

test_that("Function show_seq_logo() @ L24", {
  
  p1 <- show_seq_logo(sapply(split(LETTERS[1:24], 1:4), function(x) paste0(x, collapse = "")))
  p1
  p2 <- show_seq_logo(sapply(split(LETTERS[1:24], 1:4), function(x) paste0(x, collapse = "")),
    recode = TRUE
  )
  p2
  p3 <- show_seq_logo(sapply(split(LETTERS[1:6], 1:2), function(x) paste0(x, collapse = "")),
    simple_version = TRUE
  )
  expect_is(p1, "ggplot")
  expect_is(p2, "ggplot")
  expect_is(p3, "ggplot")
})

