# Generated by roxytest: Do not edit by hand!

context("File R/seq_motif_finder.R: @testexamples")

test_that("Function sh_build_sub_matrix() @ L50", {
  
  sub_list <- sh_build_sub_matrix
  expect_is(sub_list, "list")
})

