# Generated by roxytest: Do not edit by hand!

context("File R/get_score_matrix.R: @testexamples")

test_that("Function get_score_matrix() @ L77", {
  
  load(system.file("extdata", "toy_segTab.RData",
    package = "CNVMotif", mustWork = TRUE
  ))
  x <- transform_seqs(segTabs)
  x
  seqs <- extract_seqs(x$dt)
  seqs
  seqs2 <- extract_seqs(x$dt, flexible_approach = TRUE)
  seqs2
  
  mat <- get_score_matrix(seqs$keep, x$mat, verbose = TRUE)
  mat
  
  mat2 <- get_score_matrix(seqs$keep, x$mat, dislike = TRUE)
  identical(mat2, 120L - mat)
  
  mat_b <- get_score_matrix(seqs$keep, x$mat, block_size = 2L)
  ## block1 represents the first 2 sequences
  ## block2 represents the 3rd, 4th sequences
  ## ...
  mat_b
  
  mat_c <- get_score_matrix(seqs$keep)
  mat_c
  mat_d <- get_score_matrix(seqs$keep, dislike = TRUE)
  mat_d
  
  if (require("doParallel")) {
    mock_seqs <- sapply(1:10000, function(x) {
      paste(sample(LETTERS[1:24], 5, replace = TRUE), collapse = "")
    })
  
    system.time(
      y1 <- get_score_matrix(mock_seqs, x$mat, cores = 1)
    )
  
    system.time(
      y2 <- get_score_matrix(mock_seqs, x$mat, cores = 2)
    )
  
    all.equal(y1, y2)
  }
  
  expect_is(x, "list")
  expect_is(seqs, "list")
  expect_is(seqs2, "character")
  expect_is(mat, "matrix")
  expect_is(mat_b, "matrix")
  expect_is(mat_c, "matrix")
  expect_is(mat_d, "matrix")
  expect_equal(mat2, 120L - mat)
  if (require("doParallel")) {
    expect_equal(y1, y2)
  }
})

