# Generated by roxytest: Do not edit by hand!

context("File R/show_seq_shape.R: @testexamples")

test_that("Function show_seq_shape() @ L23", {
  
  p <- show_seq_shape(c("ADGHK"))
  p
  x <- list(a = c("ABCDE", "AXFDP"), b = c("KKDFH", "GKDFM"))
  p2 <- show_seq_shape(x)
  p2
  expect_is(p, "ggplot")
  expect_is(p2, "ggplot")
})

