# Generated by roxytest: Do not edit by hand!

context("File R/seq_motif_finder.R: @testexamples")

test_that("Function sh_build_sub_matrix() @ L86", {
  
  sub_list <- sh_build_sub_matrix()
  sub_list2 <- sh_build_sub_matrix(simple_version = TRUE)
  expect_is(sub_list, "list")
  expect_is(sub_list2, "list")
})


test_that("Function sh_get_score_matrix() @ L305", {
  
  load(system.file("extdata", "toy_segTab.RData",
    package = "CNVMotif", mustWork = TRUE
  ))
  x <- sh_coding_segs(segTabs)
  x
  seqs <- sh_extract_seqs(x$dt)
  seqs
  seqs2 <- sh_extract_seqs(x$dt, flexible_approach = TRUE)
  seqs2
  
  mat <- sh_get_score_matrix(seqs$keep, x$mat, verbose = TRUE)
  mat
  
  mat2 <- sh_get_score_matrix(seqs$keep, x$mat, dislike = TRUE)
  identical(mat2, 120L - mat)
  
  mat_b <- sh_get_score_matrix(seqs$keep, x$mat, block_size = 2L)
  ## block1 represents the first 2 sequences
  ## block2 represents the 3rd, 4th sequences
  ## ...
  mat_b
  
  mat_c <- sh_get_score_matrix(seqs$keep)
  mat_c
  mat_d <- sh_get_score_matrix(seqs$keep, dislike = TRUE)
  mat_d
  
  if (require("doParallel")) {
    mock_seqs <- sapply(1:10000, function(x) {
      paste(sample(LETTERS[1:24], 5, replace = TRUE), collapse = "")
    })
  
    system.time(
      y1 <- sh_get_score_matrix(mock_seqs, x$mat, cores = 1)
    )
  
    system.time(
      y2 <- sh_get_score_matrix(mock_seqs, x$mat, cores = 2)
    )
  
    all.equal(y1, y2)
  }
  
  expect_is(x, "list")
  expect_is(seqs, "list")
  expect_is(seqs2, "character")
  expect_is(mat, "matrix")
  expect_is(mat_b, "matrix")
  expect_is(mat_c, "matrix")
  expect_is(mat_d, "matrix")
  expect_equal(mat2, 120L - mat)
  if (require("doParallel")) {
    expect_equal(y1, y2)
  }
})


test_that("Function show_seq_shape() @ L457", {
  
  p <- show_seq_shape(c("ADGHK"))
  p
  x <- list(a = c("ABCDE", "AXFDP"), b = c("KKDFH", "GKDFM"))
  p2 <- show_seq_shape(x)
  p2
  expect_is(p, "ggplot")
  expect_is(p2, "ggplot")
})


test_that("Function show_seq_logo() @ L573", {
  
  p1 <- show_seq_logo(sapply(split(LETTERS[1:24], 1:4), function(x) paste0(x, collapse = "")))
  p1
  p2 <- show_seq_logo(sapply(split(LETTERS[1:24], 1:4), function(x) paste0(x, collapse = "")),
    recode = TRUE
  )
  p2
  p3 <- show_seq_logo(sapply(split(LETTERS[1:6], 1:2), function(x) paste0(x, collapse = "")),
    simple_version = TRUE
  )
  expect_is(p1, "ggplot")
  expect_is(p2, "ggplot")
  expect_is(p3, "ggplot")
})

