# Generated by roxytest: Do not edit by hand!

context("File R/cluster_pam.R: @testexamples")

test_that("Function cluster_pam_estimate() @ L26", {
  
  data("iris")
  head(iris)
  iris.scaled <- scale(iris[, -5])
  iris.dist <- dist(iris.scaled) %>% as.matrix()
  p <- cluster_pam_estimate(iris.dist)
  p2 <- cluster_pam_estimate(iris.dist, method = "wss")
  
  cl <- cluster_pam(iris.dist, 3)
  expect_is(p, "ggplot")
  expect_is(p2, "ggplot")
  expect_is(cl, "pam")
})

