# Generated by roxytest: Do not edit by hand!

context("File R/build_sub_matrix.R: @testexamples")

test_that("Function build_sub_matrix() @ L16", {
  
  sub_list <- build_sub_matrix()
  sub_list2 <- build_sub_matrix(simple_version = TRUE)
  expect_is(sub_list, "list")
  expect_is(sub_list2, "list")
})

