# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pairScoreVector <- function(x, y, x_max, y_max) {
    .Call(`_sigminer_helper_pairScoreVector`, x, y, x_max, y_max)
}

pairScoreMatrix <- function(x, y, x_max, y_max) {
    .Call(`_sigminer_helper_pairScoreMatrix`, x, y, x_max, y_max)
}

pairScoreSimpleVector <- function(x, y, max) {
    .Call(`_sigminer_helper_pairScoreSimpleVector`, x, y, max)
}

pairScoreSimpleMatrix <- function(x, y, max) {
    .Call(`_sigminer_helper_pairScoreSimpleMatrix`, x, y, max)
}

getScoreMatrix <- function(indexMat, subMat, bSize, like, verbose) {
    .Call(`_sigminer_helper_getScoreMatrix`, indexMat, subMat, bSize, like, verbose)
}

getScoreMatrixRect <- function(indexMat1, indexMat2, subMat, like, verbose) {
    .Call(`_sigminer_helper_getScoreMatrixRect`, indexMat1, indexMat2, subMat, like, verbose)
}

